### ISSUE TITLE
Outdated JS file

### ISSUE THREAD

**Issue by COConsulting** [TheDartCode/typedjs-rails#4]
It looks like this gem has not been updated in 3 years and there is a newer version of the js file available with additional functionality. Can the maintainer of this gem update the code?

**Comment by TheDartCode** [comment]
Code updated, thanks for the heads up.

**Comment by COConsulting** [comment]
I appreciate the quick response. But, after I update the gem in my Gemfile to 2.0.9 and run bundle install, it updates the gem and the functionality of the type.js is no longer working. As in, it no longer types out the phrases. I rolled back to the previous version, 1.0.4, and it worked again. Please advise.

**Comment by TheDartCode** [comment]
v2 of typedjs has a slightly different api than v1.
Have you checked it?
https://github.com/mattboldt/typed.js/#setup
